const getnotif=(req,res)=>{
    res.json({
        "status": true,
        "message": "Berhasil mendapatkan notifikasi",
        "data": [
            {
                "notifId": "139284",
                "sourceId": "130913848001",
                "sourceName": "Dzakhwan Djalaluddin M Akbar",
                "classlevelid": "4",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-07-22 14:13:15",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": "http://images.ganeshaoperation.com/gokreasi/feed/981123000001/033af7bf2f5c1f0c3f395dee036ecfd7.jpeg",
                    "feedId": 26353,
                    "isLike": 1,
                    "status": "publik",
                    "content": "[FLEXING TRYOUT]\nHai guys, saya dapat nilai tryout segini loh!\nJangan mau kalah ya Sobat",
                    "tanggal": "2023-06-13 14:55:52.000000",
                    "fullname": "DZAKHWAN DJALALUDDIN M AKBAR",
                    "creatorId": "981123000001",
                    "totalLike": 1
                }
            },
            {
                "notifId": "125777",
                "sourceId": "050105114703",
                "sourceName": "Ricko Juriaman",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-07-01 11:04:28",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": "http://images.ganeshaoperation.com/gokreasi/feed/981123000001/033af7bf2f5c1f0c3f395dee036ecfd7.jpeg",
                    "feedId": 26353,
                    "isLike": 1,
                    "status": "publik",
                    "content": "[FLEXING TRYOUT]\nHai guys, saya dapat nilai tryout segini loh!\nJangan mau kalah ya Sobat",
                    "tanggal": "2023-06-13 14:55:52.000000",
                    "fullname": "Ricko Juriaman",
                    "creatorId": "981123000001",
                    "totalLike": 1
                }
            },
            {
                "notifId": "108609",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-19 08:04:56",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": "http://images.ganeshaoperation.com/gokreasi/feed/981123000002/a0b956a2bdec0098554c81b0350cddc9.jpeg",
                    "feedId": 21960,
                    "isLike": 1,
                    "status": "publik",
                    "content": "[FLEXING RANKING]\nHai guys, wah saya ranking 290 Gedung lohhh.\nJangan mau kalah yaaa",
                    "tanggal": "2023-03-19 08:05:48.000000",
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": "981123000002",
                    "totalLike": 1
                }
            },
            {
                "notifId": "105606",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-08 18:09:43",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "105365",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-07 23:11:09",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "105364",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-07 23:08:30",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "104729",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-05 17:14:52",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "104648",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-04 21:03:08",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "104647",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-04 21:02:35",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "104646",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-04 21:02:00",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "104645",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-04 21:00:57",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "103606",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-03-01 16:40:39",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "103431",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-02-28 20:01:48",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "103432",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-02-28 19:59:21",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            },
            {
                "notifId": "103430",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-02-28 19:58:48",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": "http://images.ganeshaoperation.com/gokreasi/feed/981123000001/36ec3908774622046d40490586884d52.jpeg",
                    "feedId": 21934,
                    "isLike": 1,
                    "status": "hapus",
                    "content": "[FLEXING RANKING]\nHai guys, wah saya ranking 8107 Nasional lohhh.\nJangan mau kalah yaaa",
                    "tanggal": "2023-02-28 13:32:52.000000",
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": "981123000001",
                    "totalLike": 1
                }
            },
            {
                "notifId": "101114",
                "sourceId": "981123000001",
                "sourceName": "Rahmad Farizan",
                "classlevelid": "14",
                "role": "SISWA",
                "notifType": "comment new",
                "isSeen": true,
                "date": "2023-02-21 12:06:38",
                "className": "12-IPA-R-N-103",
                "info": {
                    "role": "SISWA",
                    "image": null,
                    "feedId": null,
                    "isLike": 0,
                    "status": null,
                    "content": null,
                    "tanggal": null,
                    "fullname": "RAHMAD FARIZAN",
                    "creatorId": null,
                    "totalLike": 0
                }
            }
        ]
    })
}

module.exports={
    getnotif
}